name: nesforgains
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.3
  sqflite: ^2.4.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  path: ^1.9.0
  logger: ^2.3.0
  # For DateTimeFormatInFrontend
  intl: ^0.17.0
  # For AWS
  http: ^1.2.2
  aws_common: ^0.3.0
  aws_signature_v4: ^0.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - .env
